// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package models

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson97068512Decode20182YetAnotherGameDomainViewmodels(in *jlexer.Lexer, out *ScoreboardPageViewModel) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "Scoreboard":
			(out.Scoreboard).UnmarshalEasyJSON(in)
		case "CanNext":
			out.CanNext = bool(in.Bool())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson97068512Encode20182YetAnotherGameDomainViewmodels(out *jwriter.Writer, in ScoreboardPageViewModel) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Scoreboard\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		(in.Scoreboard).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"CanNext\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Bool(bool(in.CanNext))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ScoreboardPageViewModel) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson97068512Encode20182YetAnotherGameDomainViewmodels(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ScoreboardPageViewModel) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson97068512Encode20182YetAnotherGameDomainViewmodels(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ScoreboardPageViewModel) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson97068512Decode20182YetAnotherGameDomainViewmodels(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ScoreboardPageViewModel) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson97068512Decode20182YetAnotherGameDomainViewmodels(l, v)
}
